# Generated by Django 5.0.1 on 2024-01-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=30)),
                ('skills', models.TextField(max_length=100)),
                ('about_you', models.TextField(max_length=100)),
                ('previous_work', models.TextField(max_length=100)),
            ],
        ),
    ]
